### ISSUE TITLE
How do I get the kitten to scratch the walls?

### ISSUE THREAD

**Issue by PhoenixDreaming** [adryd325/oneko.js#12]
The animations are in the GIF file and the code appears to be there, but when I idle near the 'wall' of my site, the kitten won't scratch the walls.

**Comment by adryd325** [comment]
The cat will scratch walls when on the complete edge of the page

**Comment by DarkReaper231** [comment]
> The cat will scratch walls when on the complete edge of the page

It doesn't seem like it can get to the edge of the page tho, the furthest it can get is here
![image](https://github.com/adryd325/oneko.js/assets/38611351/0661ebf1-d212-4c2b-9082-d7b0536bb68a)
