### ISSUE TITLE
oneko not working

### ISSUE THREAD

**Issue by Razor7100** [adryd325/oneko.js#22]
I'm not sure what I'm doing wrong but its not working for me.

**Comment by Razor7100** [comment]
The file path for gif in the JavaScript is correct, I'm also loading the oneko JavaScript from the correct locations.

**Comment by dualfighter1** [comment]
Could you post the line of code where you run the JavaScript?

**Comment by Razor7100** [comment]
`<script src="../assets/modules/oneko/oneko.js"></script>`

**Comment by Razor7100** [comment]
nvm i fixed it
