### ISSUE TITLE
Oneko is not working with the most recent JavaScript

### ISSUE THREAD

**Issue by phoenixofthestars** [adryd325/oneko.js#23]
I've called the .js file in my body tag and uploaded the .gif file but it's not showing up. Uploaded the demo file but can't see anything other than blank space.

Does the file for the cat's appearance have to be a .gif? I've got a .png that's the same size and with the separate animations in the same spots; I've just changed the colors.

**Comment by adryd325** [comment]
Make sure data-cat="" points to the correct image

for example if your assets are stored in /assets/neko/, your script tag is `<script src="/assets/neko/neko.js" data-cat="/assets/neko/neko.gif"></script`

**Comment by phoenixofthestars** [comment]
Ahh okay. So my own inexperience is the problem lol. Thank you!
