### ISSUE TITLE
Im probably dumb but how do i make animations work

### ISSUE THREAD

**Issue by dualfighter1** [adryd325/oneko.js#8]
Im trying to have the animations like sleeping and wall scratching work and they don't appear to be happening, I was waiting for a solid 2 minutes waiting for it to go to sleep.

Thanks,
Noelle

**Comment by dualfighter1** [comment]
Update: it does work but feels WAY too slow in going to extra animations, leaving me waiting like a whole 5 minutes sometimes.

**Comment by adryd325** [comment]
if you want to make the animations more frequent on your site, change 200 to a lower number on this line https://github.com/adryd325/oneko.js/blob/ad83774e23c2e9d0179b9473b96ec508e4ee5570/oneko.js#L115

**Comment by dualfighter1** [comment]
Thank you, Im new to js and dont exactly know my way around it so thanks for this :3c
